# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: check-toml
    - id: check-symlinks
    - id: check-added-large-files
    - id: check-vcs-permalinks
    - id: debug-statements
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
    - id: reorder-python-imports
      args: ["--py26-plus", "--application-directories=.:src"]

- repo: https://github.com/PyCQA/flake8
  rev: '6.0.0'
  hooks:
    - id: flake8
      args: ["--append-config", "tox.ini"]
      language_version: python3
      additional_dependencies:
      # NOTE: autoupdate does not pick up flake8-bugbear since it is a
      # transitive dependency. Make sure to update flake8-bugbear
      # manually on a regular basis.
      - flake8-bugbear==23.1.20

- repo: https://github.com/psf/black
  rev: '23.1.0'
  hooks:
    - id: black
