[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.coverage.run]
source_pkgs = ["unflatten"]
parallel = true

[tool.coverage.paths]
source = [
    "src",
    "*/site-packages",
]
