name: Tests

on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yml

  pypi-publish:
    name: Upload to PyPI
    needs: tests
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
      url: https://pypi.org/p/barnhunt
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
